steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -lc
      - |
        python3 -m pip install --no-cache-dir -r service/requirements.txt || true
        python3 training/prepare_features.py --mode offense || true
        python3 training/prepare_features.py --mode defense || true
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/$PROJECT_ID/player-sim:latest','.']
images:
  - 'gcr.io/$PROJECT_ID/player-sim:latest'